#!/usr/bin/env python3
"""Build and validate the topic DAG; emit knowledge-graph.yml (deterministic).
Exit 0 = clean. Cycles and missing prerequisites are hard errors."""

import sys
from collections import defaultdict, deque
from pathlib import Path

from _yaml_mini import parse_frontmatter

ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = ROOT / 'knowledge'
OUTPUT = ROOT / 'knowledge-graph.yml'

ERRORS = []
WARNINGS = []


def error(msg):
    ERRORS.append(msg)


def warning(msg):
    WARNINGS.append(msg)


def collect_topics():
    topics = {}
    for concept in sorted(KNOWLEDGE.rglob('concept.md')):
        rel = concept.relative_to(KNOWLEDGE)
        if len(rel.parts) != 3 or rel.parts[-1] != 'concept.md':
            error('%s: topic folders must be exactly <track>/<topic>/concept.md' % concept)
            continue
        fm, _ = parse_frontmatter(concept.read_text(encoding='utf-8'))
        if not fm:
            error('%s: missing or invalid frontmatter' % concept)
            continue
        topic_id = fm.get('id')
        expected = '%s/%s' % (rel.parts[0], rel.parts[1])
        if topic_id != expected:
            error('%s: frontmatter id %r does not match folder path %r' % (concept, topic_id, expected))
            topic_id = expected
        if topic_id in topics:
            error('duplicate topic id: %s' % topic_id)
            continue
        topics[topic_id] = {
            'title': fm.get('title', ''),
            'track': fm.get('track', ''),
            'band': fm.get('band', ''),
            'tier': fm.get('tier', ''),
            'bloom_target': fm.get('bloom_target', ''),
            'status': fm.get('status', 'draft'),
            'prerequisites': [p for p in fm.get('prerequisites', []) if p],
            'related': [r for r in fm.get('related', []) if r],
        }
        if not (concept.parent / 'validation.md').exists():
            warning('%s: missing validation.md' % topic_id)
        if not (concept.parent / 'teaching.md').exists():
            warning('%s: missing teaching.md' % topic_id)
    return topics


def check_edges(topics):
    for tid, t in sorted(topics.items()):
        for p in t['prerequisites']:
            if p == tid:
                error('%s: self-prerequisite' % tid)
            elif p not in topics:
                error('%s: prerequisite %r does not exist' % (tid, p))
        seen = set()
        for p in t['prerequisites']:
            if p in seen:
                error('%s: duplicate prerequisite %r' % (tid, p))
            seen.add(p)
        for r in t['related']:
            if r == tid:
                error('%s: self-related' % tid)
            elif r not in topics:
                warning('%s: related topic %r does not exist' % (tid, r))


def detect_cycles(topics):
    indeg = {tid: len(t['prerequisites']) for tid, t in topics.items()}
    out = defaultdict(list)
    for tid, t in topics.items():
        for p in t['prerequisites']:
            out[p].append(tid)
    queue = deque(sorted(tid for tid, d in indeg.items() if d == 0))
    order = []
    while queue:
        tid = queue.popleft()
        order.append(tid)
        for child in sorted(out[tid]):
            indeg[child] -= 1
            if indeg[child] == 0:
                queue.append(child)
    if len(order) != len(topics):
        remaining = sorted(set(topics) - set(order))
        error('cycle detected among (or orphaned by missing prerequisites): %s' % ', '.join(remaining))
        return None, []
    return order, indeg


def compute_depths(topics, order):
    depths = {}
    for tid in order:
        prereq_depths = [depths[p] for p in topics[tid]['prerequisites']]
        depths[tid] = 1 + max(prereq_depths) if prereq_depths else 1
    return depths


def emit_graph(topics, depths):
    waves = defaultdict(list)
    for tid, depth in sorted(depths.items(), key=lambda kv: (kv[1], kv[0])):
        waves[depth].append(tid)
    lines = ['# knowledge-graph.yml - generated by tools/check-graph.py. Do not hand-edit.',
             'schema-version: 1',
             'topic-count: %d' % len(topics),
             'wave-count: %d' % max(waves) if waves else 'wave-count: 0',
             'topics:']
    for tid, depth in sorted(depths.items(), key=lambda kv: (kv[1], kv[0])):
        t = topics[tid]
        lines.append('  - id: %s' % tid)
        lines.append('    title: %s' % t['title'])
        lines.append('    track: %s' % t['track'])
        lines.append('    band: %s' % t['band'])
        lines.append('    tier: %s' % t['tier'])
        lines.append('    bloom_target: %s' % t['bloom_target'])
        lines.append('    status: %s' % t['status'])
        lines.append('    depth: %d' % depth)
        lines.append('    prerequisites: [%s]' % ', '.join(t['prerequisites']))
        lines.append('    related: [%s]' % ', '.join(t['related']))
    lines.append('waves:')
    for wave, ids in sorted(waves.items()):
        lines.append('  %d: [%s]' % (wave, ', '.join(ids)))
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main():
    topics = collect_topics()
    check_edges(topics)
    order, _ = detect_cycles(topics)
    if order is None:
        for w in WARNINGS:
            print('WARN: %s' % w)
        for e in ERRORS:
            print('ERROR: %s' % e)
        sys.exit(1)
    depths = compute_depths(topics, order)
    emit_graph(topics, depths)
    for w in WARNINGS:
        print('WARN: %s' % w)
    for e in ERRORS:
        print('ERROR: %s' % e)
    if ERRORS:
        print('check-graph failed: %d error(s)' % len(ERRORS))
        sys.exit(1)
    print('check-graph OK: %d topics, %d waves' % (len(topics), len(set(depths.values()))))


if __name__ == '__main__':
    main()
