#!/usr/bin/env python3
"""Coverage audit vs standards maps; writes docs/coverage-report.md
(deterministic). Exit 0 always (the report is informational)."""

import re
from pathlib import Path

from _yaml_mini import parse_frontmatter

ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = ROOT / 'knowledge'
STANDARDS = ROOT / 'standards'
OUTPUT = ROOT / 'docs' / 'coverage-report.md'

MAPS = [
    ('SWEBOK v4.0 (IEEE CS)', 'swebok-map.md'),
    ('CS2023 (ACM/IEEE-CS/AAAI)', 'cs2023-map.md'),
    ('ISO/IEC 25010:2023', 'iso25010-map.md'),
    ('ISO/IEC/IEEE 12207:2017', 'iso12207-map.md'),
    ('CMMI V3.0 (ISACA)', 'cmmi-map.md'),
]

TOPIC_ID = re.compile(r'`([a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*)`')
HEADING = re.compile(r'^(#+)\s+(.+)$')


def inventory():
    ids = set()
    by_status = {}
    if KNOWLEDGE.exists():
        for concept in KNOWLEDGE.rglob('concept.md'):
            fm, _ = parse_frontmatter(concept.read_text(encoding='utf-8'))
            if fm and fm.get('id'):
                ids.add(fm['id'])
                by_status[fm['id']] = fm.get('status', 'draft')
    return ids, by_status


def parse_map(path):
    sections = []
    current = None
    for raw in path.read_text(encoding='utf-8').splitlines():
        m = HEADING.match(raw)
        if m and m.group(1).startswith('##'):
            current = {'name': m.group(2).strip(), 'ids': []}
            sections.append(current)
        elif current is not None:
            for tid in TOPIC_ID.findall(raw):
                if tid not in current['ids']:
                    current['ids'].append(tid)
    return sections


def main():
    all_ids, by_status = inventory()
    existing = [name for name, fname in MAPS if (STANDARDS / fname).exists()]
    if not existing:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(
            '# Coverage report\n\n'
            '> Generated by `tools/coverage.py` — do not hand-edit.\n\n'
            'Status: **standards maps not yet present** (created in Phase 1, task 1.1). '
            'No coverage audit possible until then.\n', encoding='utf-8')
        print('coverage: maps pending (Phase 1); report written')
        return

    lines = ['# Coverage report',
             '',
             '> Generated by `tools/coverage.py` — do not hand-edit.',
             '',
             'Inventory: **%d topics** (published: %d)' % (
                 len(all_ids), sum(1 for s in by_status.values() if s == 'published')),
             '',
             '## Summary',
             '',
             '| Standard | expected | covered | missing | coverage |',
             '|---|---|---|---|---|']
    total_expected = total_covered = 0
    for name, fname in MAPS:
        path = STANDARDS / fname
        if not path.exists():
            lines.append('| %s | — | — | — | maps pending |' % name)
            continue
        sections = parse_map(path)
        expected = [tid for s in sections for tid in s['ids']]
        covered = [tid for tid in expected if tid in all_ids]
        missing = sorted(set(expected) - set(all_ids))
        pct = (100.0 * len(covered) / len(expected)) if expected else 0.0
        total_expected += len(expected)
        total_covered += len(covered)
        lines.append('| %s | %d | %d | %d | %.0f%% |' % (name, len(expected), len(covered), len(missing), pct))
        lines.append('')
        lines.append('### %s' % name)
        lines.append('')
        lines.append('Missing (%d): %s' % (len(missing), ', '.join('`%s`' % m for m in missing) if missing else 'none'))
        lines.append('')
    if total_expected:
        lines.append('**Overall: %d/%d topics mapped (%.0f%%)**' % (
            total_covered, total_expected, 100.0 * total_covered / total_expected))
        lines.append('')
    lines.append('## Interpretation')
    lines.append('')
    lines.append('- A standards map lists the topic ids that should eventually exist to cover that standard.')
    lines.append('- Missing topics are expected during early phases; the report is a roadmap, not a failure.')
    lines.append('- Topics not claimed by any map are tracked separately below.')
    lines.append('')
    mapped = set()
    for name, fname in MAPS:
        path = STANDARDS / fname
        if path.exists():
            for s in parse_map(path):
                mapped.update(s['ids'])
    unmapped = sorted(all_ids - mapped)
    lines.append('Unmapped topics (%d): %s' % (len(unmapped), ', '.join('`%s`' % u for u in unmapped) if unmapped else 'none'))
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('coverage OK: %d/%d expected topics mapped (%.0f%%)' % (
        total_covered, total_expected, 100.0 * total_covered / total_expected if total_expected else 0.0))


if __name__ == '__main__':
    main()
