#!/usr/bin/env python3
"""Generate INDEX.md from the live topic inventory (deterministic output)."""

from pathlib import Path

from _yaml_mini import parse as parse_yaml
from _yaml_mini import parse_frontmatter

ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = ROOT / 'knowledge'
TRACKS_FILE = ROOT / 'tracks.yml'
OUTPUT = ROOT / 'INDEX.md'

BAND_ORDER = ['B6', 'B5', 'B4', 'B3', 'B2', 'B1', 'B0']


def collect_topics():
    topics = []
    for concept in sorted(KNOWLEDGE.rglob('concept.md')):
        rel = concept.relative_to(KNOWLEDGE)
        if len(rel.parts) != 3 or rel.parts[-1] != 'concept.md':
            continue
        fm, _ = parse_frontmatter(concept.read_text(encoding='utf-8'))
        if not fm:
            continue
        topics.append({
            'id': fm.get('id', '%s/%s' % (rel.parts[0], rel.parts[1])),
            'title': fm.get('title', ''),
            'band': fm.get('band', ''),
            'tier': fm.get('tier', ''),
            'bloom_target': fm.get('bloom_target', ''),
            'status': fm.get('status', 'draft'),
            'track': fm.get('track', rel.parts[0]),
        })
    return topics


def main():
    tracks = []
    if TRACKS_FILE.exists():
        data = parse_yaml(TRACKS_FILE.read_text(encoding='utf-8'))
        tracks = data.get('tracks', [])
    topics = collect_topics()
    counts = {'draft': 0, 'validated': 0, 'published': 0}
    for t in topics:
        counts[t['status']] = counts.get(t['status'], 0) + 1
    lines = ['# INDEX — all topics',
             '',
             '> Generated by `tools/index.py` — do not hand-edit; commit after regeneration.',
             '',
             '**%d topics** (%d draft · %d validated · %d published)' % (
                 len(topics), counts['draft'], counts['validated'], counts['published']),
             '',
             'Navigation: `OVERVIEW.md` → this index → `knowledge/<track>/<topic>/concept.md`.',
             'Band = abstraction level (B6 high → B0 low). Tier = evidence confidence (T0..T4).',
             'Bloom = learner target depth (remember → create). Status: draft → validated → published.',
             '']
    if tracks:
        lines.append('Track order: ' + ', '.join('`%s`' % t for t in tracks))
        lines.append('')
    for track in tracks:
        track_topics = sorted(
            (t for t in topics if t['track'] == track),
            key=lambda t: (BAND_ORDER.index(t['band']) if t['band'] in BAND_ORDER else 99, t['id']))
        if not track_topics:
            continue
        lines.append('## %s' % track)
        lines.append('')
        lines.append('| id | title | band | tier | bloom | status |')
        lines.append('|---|---|---|---|---|---|')
        for t in track_topics:
            lines.append('| `%s` | %s | %s | %s | %s | %s |' % (
                t['id'], t['title'], t['band'], t['tier'], t['bloom_target'], t['status']))
        lines.append('')
    lines.append('## Legend')
    lines.append('')
    lines.append('- **band**: abstraction axis — B6 enterprise, B5 system, B4 application, B3 module/language, B2 runtime/OS, B1 ISA/hardware, B0 microarchitecture')
    lines.append('- **tier**: evidence — T0 formal proof, T1 strong empirical, T2 codified standard, T3 established practice, T4 frontier (volatile)')
    lines.append('- **bloom**: target learner depth per Anderson & Krathwohl (2001)')
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('index OK: %d topics, %d tracks' % (len(topics), len(tracks)))


if __name__ == '__main__':
    main()
